name: Build

on: [push]

jobs:
  build:
    runs-on: macOS-10.14

    steps:
    - name: Install Hub
      run: brew install hub
    - name: Install fastlane
      run: sudo gem install fastlane -NV
    - uses: actions/checkout@v1
    - name: Build
      run: fastlane gym
    - name: Compress
      run: zip -r dmenu-mac.zip dmenu-mac.app
    - name: Release
      if: startsWith(github.ref, 'refs/tags/')
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        GITHUB_USER: "user"
      run: hub release edit $GITHUB_REF -a dmenu-mac.zip -m ''
